# -*- coding: utf-8 -*-
"""drug_label_analysis_v5__6_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvNcqEyhEZFjgBimcOlcuVXfK8pydZrs
"""

# GPU check — run this first before anything else
import torch
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("WARNING: Running on CPU — NLI inference will be very slow.")
    print("Go to Runtime -> Change runtime type -> T4 GPU")

"""###Install libraries"""

!pip install -q vaderSentiment spacy requests pandas beautifulsoup4 lxml transformers torch sentence-transformers
!python -m spacy download en_core_web_sm -q

"""## Load"""

import requests, zipfile, io
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import spacy
from bs4 import BeautifulSoup
from transformers import pipeline

nlp = spacy.load("en_core_web_sm")
##
# Zero-shot NLI severity scorer
# We score each warning block against two hypotheses and take the
# difference as a directional "regulatory severity" signal.
_nli = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli",
    device=0,
)
CAUSAL_SEVERE_HYPOTHESIS = "This drug label makes direct, unhedged assertions that the drug causes specific harmful outcomes."
CAUSAL_MILD_HYPOTHESIS   = "This drug label describes potential risks tentatively, using uncertain or qualified language."
CAUSAL_HYPOTHESIS = [CAUSAL_SEVERE_HYPOTHESIS, CAUSAL_MILD_HYPOTHESIS]
OUTCOME_SEVERE_HYPOTHESIS = "This drug label describes risks that are life-threatening, fatal, or cause permanent harm."
OUTCOME_MILD_HYPOTHESIS = "This drug label describes risks that are mild, temporary, or reversible."
OUTCOME_HYPOTHESIS = [OUTCOME_SEVERE_HYPOTHESIS, OUTCOME_MILD_HYPOTHESIS]
POPULATION_SEVERE_HYPOTHESIS =  "This drug label describes risks that apply broadly to most or all patients taking this drug."
POPULATION_MILD_HYPOTHESIS = "This drug label describes risks that are limited to specific or narrow patient subgroups."
POPULATION_HYPOTHESIS = [POPULATION_SEVERE_HYPOTHESIS, POPULATION_MILD_HYPOTHESIS]
CLINICAL_SEVERE_HYPOTHESIS = "This drug label requires specific urgent clinical actions such as monitoring, discontinuation, or immediate intervention."
CLINICAL_MILD_HYPOTHESIS =  "This drug label describes risks without mandating specific or urgent clinical responses."
CLINICAL_HYPOTHESIS = [CLINICAL_SEVERE_HYPOTHESIS, CLINICAL_MILD_HYPOTHESIS]
HYPOTHESIS = [CAUSAL_HYPOTHESIS, OUTCOME_HYPOTHESIS, POPULATION_HYPOTHESIS, CLINICAL_HYPOTHESIS]
def score_severity(text: str) -> dict:
    truncated = " ".join(text.split()[:400])
    types = ["causal", "outcome", "population", "clinical"]
    output = {}
    for i, current_hypothesis in enumerate(HYPOTHESIS):
        result = _nli(
            truncated,
            candidate_labels=current_hypothesis,
            hypothesis_template="{}",
        )
        label_score = dict(zip(result["labels"], result["scores"]))
        p_severe = label_score.get(current_hypothesis[0], 0.0)
        p_mild   = label_score.get(current_hypothesis[1], 0.0)
        t = types[i]
        output[f"{t}_severity_score"] = round(p_severe - p_mild, 4)
        output[f"{t}_p_severe"]       = round(p_severe, 4)
        output[f"{t}_p_mild"]         = round(p_mild, 4)
    return output

print("All imports OK")

"""## DailyMed helpers"""

def search_dailymed(drug_name: str, pagesize: int = 5) -> list[dict]:
    """Search DailyMed for a drug. Returns list of results with 'setid' key."""
    r = requests.get(
        "https://dailymed.nlm.nih.gov/dailymed/services/v2/spls.json",
        params={"drug_name": drug_name, "pagesize": pagesize},
    )
    r.raise_for_status()
    return r.json()["data"]


def get_set_id(drug_name: str) -> str:
    """Convenience: return the top-ranked set_id for a drug name."""
    results = search_dailymed(drug_name)
    if not results:
        raise ValueError(f"No DailyMed results for '{drug_name}'")
    return results[0]["setid"]


def get_archive_versions(set_id: str) -> list[dict]:
    """Scrape all versioned archive entries for a set_id.
    Returns list of dicts with keys: archive_id, version, date, url.
    """
    r = requests.get(f"https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid={set_id}")
    soup = BeautifulSoup(r.text, "html.parser")
    links = soup.find_all("a", href=lambda h: h and "getArchivalFile.cfm" in h)
    versions = []
    for link in links:
        href = link["href"]
        archive_id = href.split("archive_id=")[-1].split("&")[0]
        row   = link.find_parent("tr")
        cells = row.find_all("td") if row else []
        versions.append({
            "archive_id": archive_id,
            "version":    cells[1].get_text(strip=True) if len(cells) > 1 else None,
            "date":       cells[0].get_text(strip=True) if len(cells) > 0 else None,
            "url":        f"https://dailymed.nlm.nih.gov/dailymed/getArchivalFile.cfm?archive_id={archive_id}",
        })
    return versions


def download_label_xml(download_url: str) -> BeautifulSoup:
    """Download a versioned ZIP from DailyMed and return its SPL XML as a BeautifulSoup tree."""
    r = requests.get(download_url)
    r.raise_for_status()
    z = zipfile.ZipFile(io.BytesIO(r.content))
    xml_file = next(f for f in z.namelist() if f.endswith(".xml"))
    return BeautifulSoup(z.read(xml_file), "lxml-xml")


def extract_sections(soup: BeautifulSoup) -> dict[str, str]:
    """Return {section_title: text} for every titled section in an SPL XML tree."""
    sections = {}
    for section in soup.find_all("section"):
        title = section.find("title")
        text  = section.find("text")
        if title and text:
            sections[title.get_text(strip=True)] = text.get_text(separator=" ", strip=True)
    return sections


def extract_warnings_text(sections: dict[str, str]) -> str:
    """Join all warning/precaution/boxed sections into one string."""
    keywords = {"WARN", "PRECAUTION", "BOXED"}
    return " ".join(
        text for name, text in sections.items()
        if any(kw in name.upper() for kw in keywords)
    )

"""## Linguistic feature extraction (spaCy)"""

# Expanding the set here to be in
HEDGING_WORDS = {
    # Modal auxiliaries
    "may", "might", "could", "would",
    # Verbs of hedging
    "appear", "appears", "seem", "seems", "suggest", "suggests",
    "indicate", "indicates", "believe", "believed",
    # Epistemic adjectives/adverbs
    "possibly", "potentially", "likely", "unlikely", "probable",
    "possible", "potential", "apparent", "apparently",
    "uncertain", "unclear", "suspected", "putative",
    # Conjunctive hedges
    "whether",
}
EPISTEMIC_CERTAINTY_WORDS = {
    "known", "proven", "confirmed", "established",
    "demonstrated", "shown", "documented", "verified",
}

DEONTIC_CERTAINTY_WORDS = {
    "must", "required", "required", "shall",
    "necessary", "mandatory", "contraindicated",
}
CAUSAL_PHRASES = [
    "associated with", "linked to", "leads to", "results in",
    "increased the risk", "increases the risk", "caused by",
    "due to", "attributed to",
]
NEGATED_CAUSAL = [
    "did not show", "no evidence", "failed to demonstrate",
    "not established", "no increase",
]


def extract_features(text: str) -> dict:
    """Extract interpretable linguistic features + NLI severity score."""
    doc        = nlp(text.lower())
    tokens     = [t.text for t in doc]
    text_lower = text.lower()
    word_count = max(len([t for t in doc if not t.is_punct]), 1)

    # spaCy passive: covers both 'auxpass' (older models) and 'aux:pass'
    passive_count = sum(
        1 for t in doc
        if t.dep_ in {"auxpass", "aux:pass"}
    )
    causal_hits     = sum(text_lower.count(p) for p in CAUSAL_PHRASES)
    neg_causal_hits = sum(text_lower.count(p) for p in NEGATED_CAUSAL)

    features = {
        "passive_rate":           passive_count / word_count,
        "hedging_rate":             sum(1 for t in tokens if t in HEDGING_WORDS) / word_count,
        "epistemic_certainty_rate": sum(1 for t in tokens if t in EPISTEMIC_CERTAINTY_WORDS) / word_count,
        "deontic_certainty_rate":   sum(1 for t in tokens if t in DEONTIC_CERTAINTY_WORDS) / word_count,
        "causal_rate":            causal_hits     / word_count,
        "negated_causal_rate":    neg_causal_hits / word_count,
        "word_count":             word_count,
    }

    features.update(score_severity(text))
    return features

"""## Full pipeline"""

def build_drug_dataframe(drug_name: str) -> pd.DataFrame:
    """
    End-to-end: search DailyMed → scrape archive → download each version →
    extract features → return a tidy DataFrame sorted by date.

    Key columns:
      severity_score  P(severe) - P(mild) — the main directional sentiment signal
      p_severe        raw probability of severe/life-threatening framing
      p_mild          raw probability of mild/permissive framing
      hedging_rate, certainty_rate, passive_rate, causal_rate, negated_causal_rate
    """
    print(f"[{drug_name}] looking up set_id …")
    set_id   = get_set_id(drug_name)
    versions = get_archive_versions(set_id)
    print(f"[{drug_name}] found {len(versions)} archived versions (set_id={set_id})")

    rows = []
    for v in versions:
        try:
            soup     = download_label_xml(v["url"])
            sections = extract_sections(soup)
            warnings = extract_warnings_text(sections)
            if not warnings:
                continue
            features = extract_features(warnings)
            rows.append({
                "drug":          drug_name,
                "version":       v["version"],
                "date":          v["date"],
                "warnings_text": warnings,
                **features,
            })
        except Exception as e:
            print(f"  version {v['version']} failed: {e}")

    df = pd.DataFrame(rows)
    df["date"]    = pd.to_datetime(df["date"], format="mixed")
    df["version"] = df["version"].str.strip().str.split("").str[0]
    df = df.sort_values("date").reset_index(drop=True)
    return df

"""## Plotting"""

# severity_score is the headline metric; spaCy features give interpretability
PLOT_METRICS = [
("causal_severity_score", "Causal Severity Score\n(P(severe) − P(mild))", "crimson"),
    ("outcome_severity_score",            "outcome severity score",                          "darkorange"),
    ("population_severity_score",              "population severity score",                                "steelblue"),
    ("clinical_severity_score",              "clinical severity score",                                "gray"),
    ("hedging_rate",        "Hedging Rate",                                        "darkorange"),
    ("epistemic_certainty_rate", "Epistemic Certainty Rate", "firebrick"),
    ("deontic_certainty_rate",   "Deontic Certainty Rate",   "darkred"),
    ("passive_rate",        "Passive Voice Rate",                                  "seagreen"),
    ("causal_rate",         "Causal Attribution Rate",                             "purple"),
    ("negated_causal_rate", "Negated-Causal Rate",                                 "gray"),
]


def plot_drug(df: pd.DataFrame, drug_name: str, metrics: list = None):
    """Plot all features over time. severity_score is shown first and largest."""
    if metrics is None:
        metrics = PLOT_METRICS

    # Give severity_score a taller subplot
    height_ratios = [2] + [1] * (len(metrics) - 1)
    fig, axes = plt.subplots(
        len(metrics), 1,
        figsize=(13, 2.5 * len(metrics)),
        sharex=True,
        gridspec_kw={"height_ratios": height_ratios},
    )
    fig.suptitle(
        f"{drug_name.title()} — Warning-Section Linguistic Features Over Time",
        fontsize=14, y=1.01,
    )

    for ax, (col, label, color) in zip(axes, metrics):
        ax.plot(df["date"], df[col], marker="o", color=color, linewidth=2)
        ax.set_ylabel(label, fontsize=8)
        ax.grid(True, alpha=0.3)
        if col == "severity_score":
            ax.axhline(0, color="black", linewidth=0.8, linestyle="--", alpha=0.4)

    axes[-1].set_xlabel("Date")
    plt.tight_layout()
    fname = f"{drug_name.lower().replace(' ', '_')}_features.png"
    plt.savefig(fname, dpi=150, bbox_inches="tight")
    print(f"Saved → {fname}")
    plt.show()

"""## Run for individual drugs:"""

import torch
print("CUDA available:", torch.cuda.is_available())

# ── Drug Candidate Scanner ──────────────────────────────────────────────────
# Candidate drugs selected to represent diverse therapeutic classes and
# regulatory histories, spanning commonly prescribed drug classes in the US
# outpatient setting (ClinCalc DrugStats 2023, Kane et al.) with emphasis
# on drugs with documented regulatory revision events. Brand-name originator
# labels used throughout as these carry complete DailyMed revision histories.
# Filtered programmatically for minimum archival depth (>= MIN_VERSIONS).
import os, time
from datetime import datetime

MIN_VERSIONS = 20

CANDIDATE_DRUGS = [
    # SSRIs / antidepressants
    "prozac", "zoloft", "lexapro", "celexa", "paxil",
    "effexor", "cymbalta", "wellbutrin", "remeron",
    # Opioids
    "oxycontin", "fentanyl", "methadone", "buprenorphine",
    "morphine", "percocet", "vicodin",
    # Antipsychotics
    "risperdal", "clozapine", "haldol", "geodon", "abilify",
    "seroquel", "zyprexa", "latuda",
    # Anticoagulants
    "xarelto", "eliquis", "coumadin", "pradaxa",
    # Statins
    "lipitor", "crestor", "zocor", "pravachol",
    # Dermatologicals / biologics
    "accutane", "humira", "enbrel", "tysabri",
    # Antihistamines
    "promethazine", "benadryl",
    # Diabetes
    "januvia", "victoza", "ozempic", "jardiance", "trulicity",
    # Sedatives / sleep
    "ambien", "xanax", "valium", "klonopin", "lunesta",
    # NSAIDs / pain
    "celebrex", "voltaren", "toradol", "advil",
    # Cardiovascular
    "toprol", "norvasc", "diovan", "cozaar", "coreg",
    # Historically significant / withdrawn
    "avandia", "thalidomide", "vioxx",
]

print(f"Total candidates: {len(CANDIDATE_DRUGS)} "
      f"({len(TIER1_CLINCALC)} tier 1 ClinCalc, "
      f"{len([d for d in TIER2_REGULATORY if d.lower() not in [t.lower() for t in TIER1_CLINCALC]])} tier 2 supplementary)")

SCAN_CACHE = "drug_scan_results.csv"

def scan_drug_archive_depth(drug_name):
    try:
        set_id = get_set_id(drug_name)
        time.sleep(0.5)
        versions = get_archive_versions(set_id)
        time.sleep(0.5)
        parsed_dates = []
        for v in versions:
            if v["date"]:
                try:
                    parsed_dates.append(datetime.strptime(v["date"], "%b %d, %Y"))
                except:
                    pass
        return {
            "drug":          drug_name,
            "set_id":        set_id,
            "n_versions":    len(versions),
            "earliest_date": min(parsed_dates).strftime("%Y-%m-%d") if parsed_dates else None,
            "latest_date":   max(parsed_dates).strftime("%Y-%m-%d") if parsed_dates else None,
            "qualifies":     len(versions) >= MIN_VERSIONS,
            "tier":          1 if drug_name in TIER1_CLINCALC else 2,
        }
    except Exception as e:
        return {
            "drug":          drug_name,
            "set_id":        None,
            "n_versions":    0,
            "earliest_date": None,
            "latest_date":   None,
            "qualifies":     False,
            "tier":          1 if drug_name in TIER1_CLINCALC else 2,
        }

if os.path.exists(SCAN_CACHE):
    print(f"Loading cached scan from {SCAN_CACHE}")
    scan_df = pd.read_csv(SCAN_CACHE)
else:
    print(f"Scanning {len(CANDIDATE_DRUGS)} candidates (threshold: >= {MIN_VERSIONS} versions)...")
    scan_results = []
    for drug in CANDIDATE_DRUGS:
        result = scan_drug_archive_depth(drug)
        status = "PASS" if result["qualifies"] else "fail"
        tier = result["tier"]
        print(f"  [T{tier}] [{status}] {drug}: {result['n_versions']} versions "
              f"({result['earliest_date']} -> {result['latest_date']})")
        scan_results.append(result)
    scan_df = pd.DataFrame(scan_results)
    scan_df.to_csv(SCAN_CACHE, index=False)
    print(f"Saved to {SCAN_CACHE}")

qualified = scan_df[scan_df["qualifies"]].sort_values("n_versions", ascending=False)
print(f"\n{len(qualified)} drugs qualify (>= {MIN_VERSIONS} versions):")
print(qualified[["drug", "tier", "n_versions", "earliest_date", "latest_date"]].to_string(index=False))

QUALIFIED_DRUGS = qualified["drug"].tolist()
print(f"\nQUALIFIED_DRUGS = {QUALIFIED_DRUGS}")

""""Candidate drugs were drawn from two sources: generic drug names from the ClinCalc DrugStats top 100 most prescribed US outpatient medications (Kane, 2023), and brand-name originator labels for drugs with documented significant regulatory revision events identified through FDA safety communications and REMS program records. Of 150 candidates, 28 met the minimum archival depth threshold of 20 archived versions in DailyMed and were retained for analysis."
"""

r = requests.get(
    "https://dailymed.nlm.nih.gov/dailymed/services/v2/spls.json",
    params={
        "doctype": "34066-1",  # LOINC code for boxed warning
        "pagesize": 100,
        "page": 1
    }
)
print(r)

# Run this once in Colab to get the REMS product list
import requests, io
import pandas as pd

# Download REMS products CSV from FDA
rems_url = "https://www.accessdata.fda.gov/scripts/cder/rems/index.cfm?event=csvRemsProduct.page"
r = requests.get(rems_url)
rems_df = pd.read_csv(io.StringIO(r.text))
print(rems_df.columns.tolist())
print(rems_df.head(10))

QUALIFIED_DRUGS = ['xarelto', 'cymbalta', 'enbrel', 'wellbutrin', 'geodon', 'risperdal', 'apixaban', 'eliquis', 'effexor', 'dulaglutide', 'clozapine', 'lexapro', 'oxycontin', 'prozac', 'victoza', 'xanax', 'tysabri', 'promethazine', 'fluoxetine', 'paxil', 'celexa', 'haldol', 'ibuprofen', 'citalopram', 'januvia', 'fentanyl', 'abilify', 'ambien']

# ── Caching wrappers ─────────────────────────────────────────────────────────
# Pickle each drug dataframe after first run. Delete .pkl to force re-run.
import pickle, os

def build_drug_dataframe_cached(drug_name):
    cache_path = f"{drug_name.lower().replace(' ', '_')}_label_cache.pkl"
    if os.path.exists(cache_path):
        print(f"[{drug_name}] loading label cache from {cache_path}")
        return pickle.load(open(cache_path, "rb"))
    df = build_drug_dataframe(drug_name)
    pickle.dump(df, open(cache_path, "wb"))
    print(f"[{drug_name}] label data cached to {cache_path}")
    return df

def build_pubmed_cached(drug_name, start_year, end_year):
    cache_path = f"{drug_name.lower().replace(' ', '_')}_pubmed_cache.pkl"
    if os.path.exists(cache_path):
        print(f"[{drug_name}] loading PubMed cache from {cache_path}")
        return pickle.load(open(cache_path, "rb"))
    df = build_pubmed_yearly(drug_name, start_year, end_year)
    pickle.dump(df, open(cache_path, "wb"))
    print(f"[{drug_name}] PubMed data cached to {cache_path}")
    return df

import transformers
transformers.logging.set_verbosity_error()

# ── Full pipeline ────────────────────────────────────────────────────────────
# Uses QUALIFIED_DRUGS from scanner. Falls back to manual list if scanner
# has not been run yet.

try:
    drugs_to_run = QUALIFIED_DRUGS
    print(f"Running pipeline on {len(drugs_to_run)} qualified drugs.")
except NameError:
    drugs_to_run = ["prozac", "oxycontin", "accutane", "warfarin",
                    "promethazine", "escitalopram"]
    print("QUALIFIED_DRUGS not set — using manual fallback list.")

label_dataframes = {}  # stored for PubMed comparison later

for drug in drugs_to_run:
    try:
        df = build_drug_dataframe_cached(drug)
        label_dataframes[drug] = df
        plot_drug(df, drug)
    except Exception as e:
        print(f"[{drug}] pipeline failed: {e}")

prozac_df = build_drug_dataframe("prozac")
plot_drug(prozac_df, "prozac")

oxycontin_df = build_drug_dataframe("oxycontin")
plot_drug(oxycontin_df, "oxycontin")

vioxx_df = build_drug_dataframe("rofecoxib")
plot_drug(vioxx_df, "rofecoxib")

zoloft_df = build_drug_dataframe("zoloft")
plot_drug(zoloft_df, "zoloft")

Accutane_df = build_drug_dataframe("Accutane")
plot_drug(Accutane_df, "Accutane")

warfarin_df = build_drug_dataframe("warfarin")
plot_drug(warfarin_df, "warfarin")

"""### Fucking Fade me. I am so exhausted. Job is not finished David.

- paroxetine, fluoxetine, escitalopram.
- Promethezine.
- Cisapride
- Terfenadine
"""

promethezine_df = build_drug_dataframe("promethazine")
plot_drug(promethezine_df, " promethazine")

Cisapride_df = build_drug_dataframe("escitalopram")
plot_drug(Cisapride_df, " escitalopram")

"""# Run as a group"""

drug_names = ["prozac", "oxycontin", "zoloft", "Accutane", "warfarin", "promethazine","escitalopram"]

def run_all(drug_names):
  for drug in drug_names:
    drug_df = build_drug_dataframe(drug)
    plot_drug(drug_df, drug)
run_all(drug_names)



"""##

Anon notes:
- Features are "specific known markers that he lingustics literature identifies as meaningful"

# Adding an extra external NLI for PubMed/text corpura outside of the drug labels.

### Fetching from PubMed:
"""

import time
import requests

def fetch_pubmed_abstracts(drug_name: str,
                            start_year: int,
                            end_year: int,
                            abstracts_per_year: int = 25) -> pd.DataFrame:
    """
    Fetch PubMed abstracts mentioning drug_name, grouped by year.
    Uses NCBI E-utilities (no API key required, but rate-limited to 3 req/sec).
    Returns DataFrame with columns: drug, year, abstract, scored features.
    """
    base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
    rows = []

    for year in range(start_year, end_year + 1):
        # Step 1: search for PMIDs
        search_params = {
            "db": "pubmed",
            "term": f"{drug_name}[tiab] AND {year}[pdat]",
            "retmax": abstracts_per_year,
            "retmode": "json",
            "sort": "relevance",
        }
        try:
            r = requests.get(f"{base_url}/esearch.fcgi", params=search_params)
            r.raise_for_status()
            pmids = r.json()["esearchresult"]["idlist"]
        except Exception as e:
            print(f"  [{drug_name}] search failed for {year}: {e}")
            time.sleep(0.5)
            continue

        if not pmids:
            print(f"  [{drug_name}] no results for {year}")
            continue

        time.sleep(0.34)  # stay under 3 req/sec without API key

        # Step 2: fetch abstracts for those PMIDs
        fetch_params = {
            "db": "pubmed",
            "id": ",".join(pmids),
            "rettype": "abstract",
            "retmode": "xml",
        }
        try:
            r = requests.get(f"{base_url}/efetch.fcgi", params=fetch_params)
            r.raise_for_status()
            soup = BeautifulSoup(r.content, "lxml-xml")
        except Exception as e:
            print(f"  [{drug_name}] fetch failed for {year}: {e}")
            time.sleep(0.5)
            continue

        time.sleep(0.34)

        # Step 3: extract and score each abstract
        abstracts = soup.find_all("AbstractText")
        year_texts = [a.get_text(separator=" ", strip=True)
                      for a in abstracts if len(a.get_text()) > 100]

        if not year_texts:
            print(f"  [{drug_name}] no usable abstracts for {year}")
            continue

        for text in year_texts:
            try:
                scores = score_severity(text)
                rows.append({
                    "drug":  drug_name,
                    "year":  year,
                    "abstract": text,
                    **scores,
                })
            except Exception as e:
                print(f"  [{drug_name}] scoring failed for {year}: {e}")

        print(f"  [{drug_name}] {year}: {len(year_texts)} abstracts scored")

    df = pd.DataFrame(rows)
    return df


def build_pubmed_yearly(drug_name: str,
                         start_year: int,
                         end_year: int) -> pd.DataFrame:
    """
    Aggregate per-abstract scores to yearly means for comparison
    against label trajectories.
    """
    df = fetch_pubmed_abstracts(drug_name, start_year, end_year)
    if df.empty:
        return df

    score_cols = [c for c in df.columns if c.endswith("_severity_score")]
    yearly = (df.groupby("year")[score_cols]
                .mean()
                .reset_index())
    yearly["drug"] = drug_name
    return yearly

def plot_pubmed_vs_label(label_df: pd.DataFrame,
                          pubmed_df: pd.DataFrame,
                          drug_name: str):
    """
    Overlay yearly mean PubMed NLI scores against label NLI scores.
    Compares trajectory shape/direction — not absolute values.
    """
    dims = ["causal", "outcome", "population", "clinical"]
    colors = {"label": "crimson", "pubmed": "steelblue"}

    fig, axes = plt.subplots(len(dims), 1,
                              figsize=(13, 3.5 * len(dims)),
                              sharex=False)
    fig.suptitle(
        f"{drug_name.title()} — Label vs. PubMed NLI Severity Trajectories\n"
        f"(trajectory shape comparable; absolute scale differs by corpus)",
        fontsize=13, y=1.01
    )

    # Convert label dates to year for alignment
    label_df = label_df.copy()
    label_df["year"] = label_df["date"].dt.year
    label_yearly = label_df.groupby("year")[
        [f"{d}_severity_score" for d in dims]
    ].mean().reset_index()

    for ax, dim in zip(axes, dims):
        col = f"{dim}_severity_score"

        # Label trajectory
        ax.plot(label_yearly["year"], label_yearly[col],
                marker="o", color=colors["label"],
                linewidth=2, label="FDA Label")

        # PubMed trajectory — secondary y-axis to handle scale difference
        ax2 = ax.twinx()
        if col in pubmed_df.columns:
            ax2.plot(pubmed_df["year"], pubmed_df[col],
                     marker="s", color=colors["pubmed"],
                     linewidth=2, linestyle="--", label="PubMed")
            ax2.set_ylabel("PubMed score", fontsize=8, color=colors["pubmed"])
            ax2.tick_params(axis="y", labelcolor=colors["pubmed"])

        ax.set_ylabel(f"{dim} severity\n(label)", fontsize=8,
                      color=colors["label"])
        ax.tick_params(axis="y", labelcolor=colors["label"])
        ax.set_title(dim.capitalize(), fontsize=9)
        ax.grid(True, alpha=0.3)
        ax.axhline(0, color="black", linewidth=0.6, linestyle="--", alpha=0.3)

        # Combined legend
        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines1 + lines2, labels1 + labels2, fontsize=8)

    axes[-1].set_xlabel("Year")
    plt.tight_layout()
    fname = f"{drug_name.lower()}_pubmed_vs_label.png"
    plt.savefig(fname, dpi=150, bbox_inches="tight")
    print(f"Saved → {fname}")
    plt.show()

# ── PubMed external validation runner ────────────────────────────────────────
# Run for selected drugs only — full 28-drug corpus would be very slow.
# Choose drugs with clear inflection points for most meaningful comparison.

PUBMED_DRUGS = ["oxycontin", "prozac", "xarelto", "cymbalta", "risperdal"]
PUBMED_START = 2006
PUBMED_END   = 2026

pubmed_dataframes = {}

for drug in PUBMED_DRUGS:
    # Get start year from label data to align windows
    if drug in label_dataframes:
        label_start = label_dataframes[drug]["date"].dt.year.min()
        start = max(PUBMED_START, int(label_start) - 1)
    else:
        start = PUBMED_START

    print(f"\nFetching PubMed abstracts for {drug} ({start}–{PUBMED_END})...")
    pubmed_df = build_pubmed_cached(drug, start, PUBMED_END)
    if not pubmed_df.empty:
        pubmed_dataframes[drug] = pubmed_df
        plot_pubmed_vs_label(label_dataframes[drug], pubmed_df, drug)
    else:
        print(f"  [{drug}] no PubMed data returned")

